# Generated by Django 3.2.4 on 2021-11-05 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('dateTime', models.DateTimeField(default=None, null=True)),
                ('todo', models.ManyToManyField(to='roadtrip.Todo')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='roadtrip.waypoint')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='roadtrip.waypoint')),
                ('waypoint', models.ManyToManyField(related_name='waypoint', to='roadtrip.Waypoint')),
            ],
        ),
    ]
