# Generated by Django 3.2.4 on 2021-11-05 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0002_todo_trip_waypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trip', to=settings.AUTH_USER_MODEL),
        ),
    ]
