# Generated by Django 3.2.4 on 2021-11-19 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0003_trip_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waypoint',
            old_name='dateTime',
            new_name='dateTimeFrom',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='dateTimeTo',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='place_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='roadtrip.waypoint'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='roadtrip.waypoint'),
        ),
    ]
