# Generated by Django 3.2.4 on 2021-11-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0004_auto_20211119_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='Trip 1', max_length=50),
            preserve_default=False,
        ),
    ]
