# Generated by Django 3.2.4 on 2021-11-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0005_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
