# Generated by Django 3.2.4 on 2021-12-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0007_auto_20211207_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendCounter',
            field=models.IntegerField(default=0),
        ),
    ]
