# Generated by Django 3.2.4 on 2021-12-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0008_user_friendcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tripCounter',
            field=models.IntegerField(default=0),
        ),
    ]
