# Generated by Django 3.2.4 on 2021-12-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0009_user_tripcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
    ]
