# Generated by Django 3.2.4 on 2021-12-12 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0012_alter_notification_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='frm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
