# Generated by Django 3.2.4 on 2021-12-20 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0013_alter_notification_frm'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='roadtrip.trip'),
        ),
    ]
