# Generated by Django 4.0.1 on 2022-01-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0016_alter_trip_name_alter_waypoint_place_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='place_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
