# Generated by Django 4.0.1 on 2022-06-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0018_rename_waypoint_trip_waypoints_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_addFriend',
            new_name='add_friend',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_inviteToTrip',
            new_name='invite_to_trip',
        ),
    ]
