# Generated by Django 4.0.1 on 2022-06-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0019_rename_is_addfriend_notification_add_friend_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
