# Generated by Django 4.0.1 on 2022-06-27 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0021_remove_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='dateFrom',
            field=models.DateField(default=datetime.datetime(2022, 6, 27, 2, 41, 8, 295019, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='dateTo',
            field=models.DateField(default=datetime.datetime(2022, 6, 27, 2, 41, 8, 295365, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='timeFrom',
            field=models.TimeField(default=datetime.datetime(2022, 6, 27, 2, 41, 8, 295354, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='timeTo',
            field=models.TimeField(default=datetime.datetime(2022, 6, 27, 2, 41, 8, 295373, tzinfo=utc), null=True),
        ),
    ]
