# Generated by Django 4.0.1 on 2022-06-27 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0022_alter_waypoint_datefrom_alter_waypoint_dateto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='dateFrom',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='dateTo',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='timeFrom',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='timeTo',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
